name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      
      - name: Create next.config.js from TypeScript
        run: yarn tsc next.config.ts --outDir .
      
      - name: Build with Next.js
        run: yarn build || echo "Build failed, will use static fallback"
      
      - name: Debug directory structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Content of out directory:"
          ls -la out || echo "out directory not found"
      
      - name: Ensure output directory exists
        run: |
          mkdir -p deploy-output
          
          # If Next.js build succeeded and out has content
          if [ -d "out" ] && [ "$(ls -A out 2>/dev/null)" ]; then
            echo "Using Next.js output"
            cp -r out/* deploy-output/
          else
            # Fallback to static HTML
            echo "Using static fallback"
            cp -r public/* deploy-output/
            
            # Ensure index.html exists
            if [ ! -f "deploy-output/index.html" ]; then
              echo '<html><head><title>MetaMask Mobile Framework Migration Validator</title></head><body><h1>MetaMask Mobile Framework Migration Validator</h1><p>This site is under construction. Please check back later.</p></body></html>' > deploy-output/index.html
            fi
          fi
          
          echo "Final deploy directory:"
          ls -la deploy-output
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy-output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 